### ISSUE TITLE
Connection failure while parent is unavailable

### ISSUE THREAD

**Issue by amemon** [eu-emi/emiregistry#15]
There are circumstances when parent is unavailable and client dsr tries to push the new events

**Comment by szigetigabor** [comment]
steps:
  1) local H2 database update (ids, new, del collection)
after the parent available again
  2) recognize the parent
  3) REGISTER, UPDATE, DELETE messages creation
  4) local H2 database cleaning
  5) code testing

**Comment by szigetigabor** [comment]
1th and 2nd step done!

**Comment by szigetigabor** [comment]
I wrote the 3rd and 4th point and commit it into the git repo, but currently I can not be tested, because I would like to start/stop the servers in my test and now it is not possible.

**Comment by amemon** [comment]
As I said earlier, this is NOT a unit test but a integration test. Hence, it is trivial to start and stop the server manually followed by running the test. The test will be similar to the earlier one that I have provided.

**Comment by szigetigabor** [comment]
The REGISTRATION is working fine.
Test scenario:
1) start the child server
2) run TestInfrastructureIntegrationSyncTestPart1 test
   It is create 2 registration message an 1 update for the http://1
3) start parent server
4) run TestInfrastructureIntegrationSyncTestPart2 test
   It is sending 1 registration to the child and check every (3) entries on the parent

**Comment by amemon** [comment]
Good work, Gabor!!! I will look into your source code by tomorrow.

**Comment by szigetigabor** [comment]
The DELETE is working fine.
I will commit the new test files.

**Comment by szigetigabor** [comment]
The UPDATE is ready.

Here is the new test scenario:
1) start the child server
2) run TestDBSyncTestPart1 test
    It is clear both (child, parent) database
    -It is create 2 registration message for http://1 and http://2            => new=1, del=0
    -and 1 update for the http://1                                                       => new=1, del=0
3) start parent server
4) run TestDBSyncTestPart2 test
   It is sending 1 registration to the child and check every (3) entries on the parent 
5) stop parent server
6) run TestDBSyncTestPart3 test
   -It is sending 2 remove message to the child (http://3 and http://non_exist)           => new=0, del=1
   -It is sending 1 update and 1 remove message for http://2                                   => 0,0 => 0,1
   -It is sending a simple update message for a http://1                                           => 0,0
   -It is sending 1 new registration and 1 remove message for http://4                      => 1,0 => remove from the list
7) start parent server
8) run TestDBSyncTestPart4 test
   -It is checking every old (3) entries on the parent http://[1-3]
   -It is sending one new registration for http://5
   -It is checking every entries on the parent
