### ISSUE TITLE
managing children at parent dsrs

### ISSUE THREAD

**Issue by amemon** [eu-emi/emiregistry#19]
It is vital to get the status/url of children dsrs. Furthermore, getting the global view of children in the registry hierarchy.

**Comment by szigetigabor** [comment]
In the Infrastructure class has "addChildDSR(String identifier)" method. This method can be pushed one identifier into the child list.
If need can I create live/ping check for every child entries.

**Comment by szigetigabor** [comment]
I create one live check method for the list.
public void childLiveCheck()

**Comment by szigetigabor** [comment]
I create a  new /children resource. The child send periodically message (one per hour) with the schema + hostname+port.
These tree element is mandatory in the DSR config otherwise the children list will be wrong.
