### ISSUE TITLE
P2P replication over Global registries

### ISSUE THREAD

**Issue by amemon** [eu-emi/emiregistry#26]

**Comment by szigetigabor** [comment]
What is need for this issue:
-configuration flag*
-start mechanism*
-neighbors resource*
-neighbors event receiver*
-service event receiver*
-one singleton class
-some modification need by the delete event generation and handling*

*done

**Comment by szigetigabor** [comment]
configuration, start mechanism, p2p package and the neighbors event receiver class is ready.

**Comment by szigetigabor** [comment]
neighbors resource and the manager class (singleton)  neighbors calculation part is done.

**Comment by szigetigabor** [comment]
I modified the delete event generation and now the events contains the deleted JSON entry.
The neighbors calculation mechanism done.

**Comment by szigetigabor** [comment]
service event receiver is done. It is send the messages to the neighbors and it put a feedback to the singleton if one neighbors is not available.

**Comment by szigetigabor** [comment]
The global DSR able to download the list of the InfoProviders and able to join to the network (get DB from one GSR of the P2P network).
Provider list structure: 
[ "provider url1" , "provider url2" , ...]  
The "[" and "]" parenthesis are optional. 

for example: [ http://emir1.hu:54321, http://emir2.de:54321 ]
