### ISSUE TITLE
unicore word elimination from the source

### ISSUE THREAD

**Issue by szigetigabor** [eu-emi/emiregistry#34]
I used the following  (grep -i "unicore" -r *|wc -l) command in the EMIR subdirectories:

emiregistry$                       101
/emiregistry/dsr$                 25
emiregistry/emir-client$       6
emiregistry/emird$               0
emiregistry/emir-dist$       54
emiregistry/xmltypes$         8

**Comment by amemon** [comment]
it would be devastating if the word "unicore" is being used as the variable names or in the distribution scripts or the pom file.

**Comment by szigetigabor** [comment]
OK but here are some examples from the emir-dist directory:

emir-dist/update-specfile.py
        jarsource="rpm/usr/share/unicore/unicorex/lib"

emir-dist/build.xml
build.xml:<project xmlns:mvn="urn:maven-artifact-ant" name="UNICORE UNICOREX Linux bundles" default="full-build">
build.xml:  <description>Build the UNICOREX Linux bundle(s)</description>
build.xml:        
build.xml:  <property name="unicorex.version" value="1.4.1-SNAPSHOT" />
build.xml:  <property name="mvn-repo-url" value="http://unicore-dev.zam.kfa-juelich.de/maven"/>
build.xml:  <property name="rpm-libs" value="${rpm-base}/usr/share/unicore/unicorex/lib"/>
build.xml:      <mvn:dependencies filesetId="unicorex.dependencies" useScope="runtime">
build.xml:          <fileset refid="unicorex.dependencies"/>
build.xml:      <mkdir dir="${rpm-base}/usr/share/doc/unicore/unicorex"/>
build.xml:      <mkdir dir="${rpm-base}/var/log/unicore/unicorex"/>
build.xml:      <mkdir dir="${rpm-base}/var/lib/unicore/unicorex"/>
build.xml:      <mkdir dir="${rpm-base}/var/run/unicore"/>
build.xml:      <copy todir="${rpm-base}/usr/share/doc/unicore/unicorex/" >
build.xml:                <delete file="target/rpm/unicore-unicorex.spec_template"/>
build.xml:          <arg value="../unicore-unicorex.spec"/>
build.xml:      <copy todir="${deb-base}/unicorex_debian" >
build.xml:          <fileset dir="${deb-src}/unicorex_debian" includ

emir-dist/main/package/distributions/Default/src/etc/emi/emir/log4j.properties:# Example logging configuration file for UNICORE CIS

emir-dist/main/package/distributions/SL6/component.spec_template:- eliminating UNICORE heritage
emir-dist/main/package/distributions/Debian/src/etc/init.d/emi-emir:# UNICORE Registry
emir-dist/main/package/distributions/Debian/debian/preinst:# preinst script for unicore-gateway
emir-dist/main/package/distributions/Debian/debian/rules:# Add here commands to install the package into debian/unicore-gateway.
emir-dist/main/package/distributions/SL5/component.spec_template:- eliminating UNICORE heritage
emir-dist/main/package/distributions/RedHat/component.spec_template:- eliminating UNICORE heritage

emir-dist/site/apt/faq.apt:*\* What is UNICORE?
emir-dist/site/apt/faq.apt:  UNICORE is a Grid middleware, enabling secure access to distributed

...

I think it would be better if the distributed packages are not contains similar failed information.
EMIR is not UNICORE Registry!
Why get answer the faq about the UNICORE or the UNICORE/X!
etc
