### ISSUE TITLE
Multi-site testbed of EMIR

### ISSUE THREAD

**Issue by amemon** [eu-emi/emiregistry#37]
The setup should be distributed enough geographically.

**Comment by szigetigabor** [comment]
It will be work only non secure mode!!!
see this issue: https://github.com/eu-emi/emiregistry/issues/40

**Comment by szigetigabor** [comment]
Two GSRs (at NIIF and at Slovakia) and one DSR (at NIIF) is available.

**Comment by amemon** [comment]
Considered Done!
