### ISSUE TITLE
Message sending problem in SSL mode

### ISSUE THREAD

**Issue by szigetigabor** [eu-emi/emiregistry#40]
Never add secure property to the client if the server is in secure mode.
Involved components:
  -SelfRegistration
  -MessageSendInThread
  -ServiceEventReceiver
  -ChildrenManager
  -ServiceCheckin
  -NeighborsManager

**Comment by szigetigabor** [comment]
I added security properties to the DSRClient object. 
https://github.com/eu-emi/emiregistry/commit/82315de5f2fb770e6fec5b2aa7daabce5523193d

**Comment by amemon** [comment]
But on the commit, the changes are being into the DSRServer class?!

**Comment by szigetigabor** [comment]
Yes, because never added security properties to the DSRClient object and now it is setting own properties to the client.  The server use the DSRClient for the message sending.

**Comment by szigetigabor** [comment]
Fetched the security information better from the server.
https://github.com/eu-emi/emiregistry/commit/52d98ba7616f218e5cec67039e4c374bf1d8c284

**Comment by amemon** [comment]
shall I close if fixed already?

**Comment by szigetigabor** [comment]
of cource.
