### ISSUE TITLE
Service update and delete failed (in DSR - GSR setup)

### ISSUE THREAD

**Issue by amemon** [eu-emi/emiregistry#59]
DSR/GSR fail to update/delete the existing endpoint records. The client however, does not receive any meaningful error messages.

**Comment by szigetigabor** [comment]
As you sad the problem comes up on http mode, but I can not reproduce it, because I can register/update/delete messages to my child DSR and it sent forward to the parent GSR.

**Comment by szigetigabor** [comment]
It was JettyServer bug and the new version of Jetty solve this issue.

**Comment by amemon** [comment]
do you point to the NIOConnector of previous jetty (8.0.4)?

**Comment by szigetigabor** [comment]
yes
