### ISSUE TITLE
Support mailing list is not accepting support requests

### ISSUE THREAD

**Issue by golbi** [eu-emi/emiregistry#65]
Hello golbi....

We're writing to let you know that the group you tried to contact (emiregistry) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
- You might have spelled or formatted the group name incorrectly.
- The owner of the group may have removed this group.
- You may need to join the group before receiving permission to post.
- This group may not be open to posting.

**Comment by amemon** [comment]
One can subscribe to the group using google groups web interface, under the following link:
https://groups.google.com/d/forum/emiregistry
