### ISSUE TITLE
Configuration change makes service restart fail at upgrade

### ISSUE THREAD

**Issue by bhagemeier** [eu-emi/emiregistry#71]
Hi there,

when upgrading from versions <1.2.0 to >=1.2.0, the configuration change -- rename of dsr.config to emir.config and various property changes -- leads to the service not being able to start. An administrator needs to manually update the emir.config file. A warning message should be issued informing the administrator that the configuration needs to be reviewed.

The change of configuration file name is not documented anywhere.

Cheers,
Björn

**Comment by amemon** [comment]
assigned to me!
