### ISSUE TITLE
No Mandatory attribute checking during the update

### ISSUE THREAD

**Issue by szigetigabor** [eu-emi/emiregistry#72]
Everybody can insert partly filled entry to the EMIR throw the update interface because it does not check the mandatory attributes.
I think it need to be validate if the entry does not exist before!

**Comment by amemon** [comment]
This has to be checked when this feature was implemented.

**Comment by szigetigabor** [comment]
Which feature?

**Comment by amemon** [comment]
inserting while using PUT? or are we talking about something else...

**Comment by szigetigabor** [comment]
I don't tested this message validation by the update! I tested only one thing: the entry created or not if does not exist before.
I realize now the message validator is in progress only the register interface.

BTW, how can we check the entry is an update or "new registration" because the mongodb inserted it if it does not exist. We need an extra query?

**Comment by amemon** [comment]
Well, this was sub-optimal! Could you please provide the fix before next update?

**Comment by szigetigabor** [comment]
Yes I will do it

**Comment by amemon** [comment]
Great!

**Comment by szigetigabor** [comment]
Fixed in this commit: https://github.com/eu-emi/emiregistry/commit/e096e613ec18e5627387382982504eef0ed9bef9
